# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wG95YXBgk3Fs1qJbj4lkzq1XC7kgGb_k
"""

import numpy as np
import matplotlib.pyplot as plt

from skimage import io
photo = io.imread('https://images-na.ssl-images-amazon.com/images/I/81KA4Aty8xL._SL1000_.jpg')
type(photo)

photo.shape

inverted_image = 255 - photo[:,:,:3]


io.imsave('test.jpg', inverted_image)
plt.imshow(inverted_image)