# -*- coding: utf-8 -*-
"""Inverting_Image.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SYShd93sAUsnENE1f7fU_IMPdV8bvDc-
"""

from skimage import io
import numpy as np
import matplotlib.pyplot as plt

pic = io.imread('colors.jpg')
print(pic.shape)

plt.imshow(pic)

pic[: ,: ,: ] = 255 - pic[: ,: ,: ]

plt.imshow(pic)